### ISSUE TITLE
[BUG] RuntimeWarning: invalid value encountered in divide

### ISSUE THREAD

**Issue by LPioL** [owkin/PyDESeq2#157]
Hi all,

**Describe the bug**
I want to use pydeseq on bulk RNA-seq data. I used salmon and the different quant.sf and so far no problem. But when I want to use dds.deseq2(), I have the following error.

My error is the following:
`Fitting size factors...
... done in 0.00 seconds.

Fitting size factors...
... done in 0.00 seconds.

/home/skynet/anaconda3/envs/pyrpipe/lib/python3.10/site-packages/pydeseq2/utils.py:917: RuntimeWarning: divide by zero encountered in divide
  ((normed_counts - y_hat) ** 2 - y_hat) / ((num_samples - num_vars) * y_hat**2)
/home/skynet/anaconda3/envs/pyrpipe/lib/python3.10/site-packages/pydeseq2/utils.py:917: RuntimeWarning: invalid value encountered in divide
  ((normed_counts - y_hat) ** 2 - y_hat) / ((num_samples - num_vars) * y_hat**2)
Fitting dispersions...
/home/skynet/anaconda3/envs/pyrpipe/lib/python3.10/site-packages/numpy/linalg/linalg.py:2120: RuntimeWarning: invalid value encountered in slogdet
  sign, logdet = _umath_linalg.slogdet(a, signature=signature)
/home/skynet/anaconda3/envs/pyrpipe/lib/python3.10/site-packages/numpy/linalg/linalg.py:2120: RuntimeWarning: invalid value encountered in slogdet
  sign, logdet = _umath_linalg.slogdet(a, signature=signature)
/home/skynet/anaconda3/envs/pyrpipe/lib/python3.10/site-packages/numpy/linalg/linalg.py:2120: RuntimeWarning: invalid value encountered in slogdet
  sign, logdet = _umath_linalg.slogdet(a, signature=signature)
/home/skynet/anaconda3/envs/pyrpipe/lib/python3.10/site-packages/numpy/linalg/linalg.py:2120: RuntimeWarning: invalid value encountered in slogdet
  sign, logdet = _umath_linalg.slogdet(a, signature=signature)
... done in 1.27 seconds.

Fitting dispersion trend curve...
/home/skynet/anaconda3/envs/pyrpipe/lib/python3.10/site-packages/statsmodels/genmod/families/family.py:188: RuntimeWarning: divide by zero encountered in divide
  return np.sum(resid_dev * freq_weights * var_weights / scale)
/home/skynet/anaconda3/envs/pyrpipe/lib/python3.10/site-packages/statsmodels/genmod/families/family.py:188: RuntimeWarning: invalid value encountered in divide
  return np.sum(resid_dev * freq_weights * var_weights / scale)
Traceback (most recent call last):
  File "/home/skynet/Documents/2023_RNA_CancerBlastema/Axolotl/RNA_analysis.py", line 299, in <module>
    dds.deseq2()
  File "/home/skynet/anaconda3/envs/pyrpipe/lib/python3.10/site-packages/pydeseq2/dds.py", line 315, in deseq2
    self.fit_dispersion_trend()
  File "/home/skynet/anaconda3/envs/pyrpipe/lib/python3.10/site-packages/pydeseq2/dds.py", line 511, in fit_dispersion_trend
    res = glm_gamma.fit()
  File "/home/skynet/anaconda3/envs/pyrpipe/lib/python3.10/site-packages/statsmodels/genmod/generalized_linear_model.py", line 1107, in fit
    return self._fit_irls(start_params=start_params, maxiter=maxiter,
  File "/home/skynet/anaconda3/envs/pyrpipe/lib/python3.10/site-packages/statsmodels/genmod/generalized_linear_model.py", line 1224, in _fit_irls
    raise ValueError("The first guess on the deviance function "
ValueError: The first guess on the deviance function returned a nan.  This could be a boundary  problem and should be reported.
`

I don't understand as my data seems clean (no sum equal to 0 for each column), and  I filtered similarly to the examples too.

Any idea ?

Thank you!

**Comment by BorisMuzellec** [comment]
Hi @LPioL, it seems like there are errors in `fit_rough_dispersions` already.

Could you check whether `dds.obsm["size_factors"]` has any 0s? 
Also, what is the shape of your design matrix (`dds.obsm["design_matrix"]`)?

**Comment by vcabeli** [comment]
Hello @LPioL,

Am I correct in understanding that you want to compare two samples, one in each condition ?
If that is the case, pydeseq2 (or deseq2) will not work : the method requires multiple samples to effectively estimate sample-specific biological variability and to perform statistical tests.

With just two samples, you could look at the log fold change for each gene but since you have no idea about the variation within each condition it will be difficult to asses the significance.
